import Head from 'next/head'
import Container from '@/components/Container'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center">
        <Container>
          <h1 className="text-xl">Pokédex</h1>
        </Container>
      </main>
    </>
  )
}
