import Head from 'next/head'
import Header from '@/components/Header'
import Container from '@/components/Container'
import { useRouter } from 'next/router'

export default function Home() {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header
        p={`Pick your favourite Pokémon and compare stats.`}
        buttonText={`Or Check em’ All Out`}
        handleClick={() => router.push('/all')}
      />
      <main className="flex flex-col items-center">
        <Container>
          <h1 className="text-xl">Pokédex</h1>
        </Container>
      </main>
    </>
  )
}
